/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Auxiliares.Auxiliar;
import Conexiones.AutoresAccess;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author sasmora
 */
public class InterfazLAB extends javax.swing.JFrame {
    
    private ArrayList<ArrayList<String>> tabla = new ArrayList<>();
    private String idAutor = "";
    private String nombreAutor = "";
    private String idPais = "";
    private String vivo = "";
    private Date fechaNacimiento = null;
    private Date fechaPublicacion = null;
    private int publicaciones = 0;
    private BigDecimal calificacion;
    private int filasAfectadas = 0;
    
    /**
     * Creates new form InterfazAutor
     */
    public InterfazLAB() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutores = new javax.swing.JTable();
        PanelIngresarDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDAutor = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        radioVivo = new javax.swing.JRadioButton();
        radioMuerto = new javax.swing.JRadioButton();
        dateNacimiento = new com.toedter.calendar.JDateChooser();
        datePublicacion = new com.toedter.calendar.JDateChooser();
        txtID_Pais = new javax.swing.JTextField();
        cmbProceso = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnAceptar = new java.awt.Button();
        spinNumPublis = new javax.swing.JSpinner();
        spinCalificacion = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        lblTitulo.setBackground(new java.awt.Color(177, 189, 201));
        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("    Autores");
        lblTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTitulo.setOpaque(true);

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));

        jTableAutores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Autor", "Nombre", "Pais", "Vivo", "FechaNacimiento", "PrimeraPublicacion", "Publicaciones", "Calificacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAutores);

        PanelIngresarDatos.setBackground(new java.awt.Color(177, 189, 201));
        PanelIngresarDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 204)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("ID Autor :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("ID Pais :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Vivo :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Primera Publicacion :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Numero de Publicaciones :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Calificacion :");

        txtIDAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDAutorActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        radioVivo.setText("Si");
        radioVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVivoActionPerformed(evt);
            }
        });

        radioMuerto.setText("No");
        radioMuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMuertoActionPerformed(evt);
            }
        });

        dateNacimiento.setDateFormatString("yyyy-MM-dd");

        datePublicacion.setDateFormatString("yyyy-MM-dd");

        txtID_Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_PaisActionPerformed(evt);
            }
        });

        cmbProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultar Todos", "Consultar uno", "Insertar", "Actualizar", "Eliminar" }));
        cmbProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProcesoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Proceso:");

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setLabel("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        spinNumPublis.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinNumPublis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinNumPublis.setFocusable(false);
        spinNumPublis.setVerifyInputWhenFocusTarget(false);
        spinNumPublis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinNumPublisMouseClicked(evt);
            }
        });

        spinCalificacion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spinCalificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinCalificacion.setFocusable(false);
        spinCalificacion.setVerifyInputWhenFocusTarget(false);
        spinCalificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinCalificacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresarDatosLayout = new javax.swing.GroupLayout(PanelIngresarDatos);
        PanelIngresarDatos.setLayout(PanelIngresarDatosLayout);
        PanelIngresarDatosLayout.setHorizontalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datePublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                            .addComponent(radioVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radioMuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtID_Pais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(spinNumPublis, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatosLayout.createSequentialGroup()
                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbProceso, 0, 140, Short.MAX_VALUE)
                            .addComponent(txtIDAutor))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        PanelIngresarDatosLayout.setVerticalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioVivo)
                    .addComponent(radioMuerto))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datePublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinNumPublis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 969, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDAutorActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void radioVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVivoActionPerformed
        // TODO add your handling code here:

        if(radioMuerto.isSelected() == true){
            radioMuerto.setSelected(false);
        }
    }//GEN-LAST:event_radioVivoActionPerformed

    private void radioMuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMuertoActionPerformed
        // TODO add your handling code here:

        if(radioVivo.isSelected() == true){
            radioVivo.setSelected(false);
        }
    }//GEN-LAST:event_radioMuertoActionPerformed

    private void txtID_PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_PaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_PaisActionPerformed

    private void cmbProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProcesoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int proceso = cmbProceso.getSelectedIndex();
        
        filasAfectadas = 0;
        
        if (proceso == 0) { //Consultar todos los autores
            tabla = AutoresAccess.getAutores();
            if (!tabla.isEmpty()) {
                Auxiliar.addTabla(tabla, jTableAutores);
            }
        } else if (proceso == 1){ //Consultar un autor
            idAutor = txtIDAutor.getText();
            if (idAutor.equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un ID de Autor", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                tabla = AutoresAccess.getAutor(idAutor);
                if (!tabla.isEmpty()) {
                    Auxiliar.addTabla(tabla, jTableAutores);
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo encontrar el autor", "Error", JOptionPane.ERROR_MESSAGE);
                }
                 clearEspacios();
            }
            
        } else if (proceso == 2) { //Insertar un autor
            if (getValores()){ //Obtener los valores de los textFields, etc;
                filasAfectadas = AutoresAccess.insertAutor(idAutor, nombreAutor, 
                    idPais, vivo, fechaNacimiento, fechaPublicacion, 
                    publicaciones, calificacion);
                clearEspacios();
            }
            JOptionPane.showMessageDialog(null, filasAfectadas + " filas fueron afectadas", "Información", JOptionPane.INFORMATION_MESSAGE);             
        } else if (proceso == 3) { //Actualizar un autor
            if (getValores()){ //Obtener los valores de los textFields, etc;
                filasAfectadas = AutoresAccess.updateAutor(idAutor, nombreAutor, 
                        idPais, vivo, fechaNacimiento, fechaPublicacion, 
                        publicaciones, calificacion);
                clearEspacios();
            }
            JOptionPane.showMessageDialog(null, filasAfectadas + " filas fueron afectadas", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else if (proceso == 4) { //Eliminar un autor
            idAutor = txtIDAutor.getText();
            if (idAutor.equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un ID de Autor", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                filasAfectadas = AutoresAccess.deleteAutor(idAutor);
                clearEspacios();
            }
            JOptionPane.showMessageDialog(null, filasAfectadas + " filas fueron afectadas", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void spinNumPublisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinNumPublisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_spinNumPublisMouseClicked

    private void spinCalificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinCalificacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_spinCalificacionMouseClicked

    
    private void clearEspacios () {
        txtIDAutor.setText("");
        txtNombre.setText("");
        txtID_Pais.setText("");
        radioMuerto.setSelected(false);
        radioVivo.setSelected(false);
        dateNacimiento.setDate(null);
        datePublicacion.setDate(null);
        spinCalificacion.setValue(0);
        spinNumPublis.setValue(0);
    }
    
    private boolean getValores () {
        idAutor = txtIDAutor.getText();
        if (idAutor.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID de Autor", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        nombreAutor = txtNombre.getText();
        if (nombreAutor.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Nombre de Autor", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        idPais = txtID_Pais.getText();
        if (idPais.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID de Pais valido", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        String tmp;
        tmp = ((JTextField) dateNacimiento.getDateEditor().getUiComponent()).getText();
        if (tmp.equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar fechas validas", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            fechaNacimiento = Date.valueOf(tmp);
        }
        
        
        tmp = ((JTextField) datePublicacion.getDateEditor().getUiComponent()).getText();
        if (tmp.equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar fechas validas", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            fechaPublicacion = Date.valueOf(tmp);
        }
        if (fechaNacimiento != null && fechaPublicacion != null){
            if (!validarFechas()) {
                return false;
            }
        }
        // Obtener fecha actual
        if (radioVivo.isSelected())
            vivo = "Y";
        else 
            vivo = "N";

        publicaciones = Integer.parseInt(spinNumPublis.getValue().toString());
        calificacion = new BigDecimal(spinCalificacion.getValue().toString());

        return true;
    }
    
    private boolean validarFechas(){
        Calendar cal = Calendar.getInstance();
        Date fechaActual = new Date(cal.getTimeInMillis());
        
        if (fechaNacimiento.after(fechaActual) || fechaPublicacion.after(fechaActual)) {
            JOptionPane.showMessageDialog(null, "Las fechas no pueden ser mayores que la fecha actual", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (fechaNacimiento.after(fechaPublicacion)) {
            JOptionPane.showMessageDialog(null, "La fecha de nacimiento debe ser anterior a la fecha de publicación", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIngresarDatos;
    private java.awt.Button btnAceptar;
    private javax.swing.JComboBox<String> cmbProceso;
    private com.toedter.calendar.JDateChooser dateNacimiento;
    private com.toedter.calendar.JDateChooser datePublicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAutores;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radioMuerto;
    private javax.swing.JRadioButton radioVivo;
    private javax.swing.JSpinner spinCalificacion;
    private javax.swing.JSpinner spinNumPublis;
    private javax.swing.JTextField txtIDAutor;
    private javax.swing.JTextField txtID_Pais;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
