/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Auxiliares.Auxiliar;
import Conexiones.RegistroVacunasAccess;
import Objetos.GLOBAL;
import Objetos.Mascota;
import Objetos.Usuario;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author sasmora
 */
public class Ven_Expediente extends javax.swing.JFrame {

    private int IDMascota;
    
    //-----Vacunas----
    
    private int IDRegistro;
    private int IDVacuna;
    private Date fechaVacuna;
    
    
    //--Diagnosticos--
    
    
    
    
    
    //-----Recetas----

    private int filasAfectadas;
    private Mascota mascota;
    
    public Ven_Expediente(Mascota mascota) {
        this.mascota = mascota;
        initComponents();
        
        Auxiliar.validarNumeros(null, txtIdDiagnostico);
        Auxiliar.validarNumeros(null, txtIdLinea);
        Auxiliar.validarNumeros(null, txtIdMascota);
        Auxiliar.validarNumeros(null, txtIdMascotaVac);
        Auxiliar.validarNumeros(null, txtIdReceta);
        Auxiliar.validarNumeros(null, txtIdRegistroVacuna);
        Auxiliar.validarNumeros(null, txtIdVeterinario);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
           /* private javax.swing.JTextField txtIdCliente4;
    private javax.swing.JTextField txtIdDiagnostico;
    private javax.swing.JTextField txtIdLinea;
    private javax.swing.JTextField txtIdMascota;
    private javax.swing.JTextField txtIdMascotaVac;
    private javax.swing.JTextField txtIdReceta;
    private javax.swing.JTextField txtIdRegistroVacuna;
    private javax.swing.JTextField txtIdVeterinario;
        */
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlDivisor2 = new javax.swing.JPanel();
        lblTitulo3 = new java.awt.Label();
        btnInicio = new java.awt.Button();
        btnPerfil = new java.awt.Button();
        lblTitulo = new java.awt.Label();
        pnlTituloNotificaciones = new javax.swing.JPanel();
        btnHistorialVacunas = new java.awt.Button();
        btnRecetas = new java.awt.Button();
        btnHistorialDiagnosticos = new java.awt.Button();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelRecetas = new javax.swing.JPanel();
        PanelIngresarDatos2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtIdReceta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        dateReceta = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtIdCliente4 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cmbProceso5 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbProcesoLineaReceta = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        btnAceptarLineaReceta = new java.awt.Button();
        jLabel31 = new javax.swing.JLabel();
        cmbProcesoReceta = new javax.swing.JComboBox<>();
        btnAceptarReceta = new java.awt.Button();
        txtIdMascota = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtIdVeterinario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEncabRecetas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLineaReceta = new javax.swing.JTable();
        PanelHistorialDeVacunas1 = new javax.swing.JPanel();
        PanelIngresarDatos1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnAceptarVacuna = new java.awt.Button();
        jLabel21 = new javax.swing.JLabel();
        txtIdRegistroVacuna = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dateVacuna = new com.toedter.calendar.JDateChooser();
        cmbVacuna = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        cmbProcesoVacuna = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        txtIdMascotaVac = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaHistorialVacunas = new javax.swing.JTable();
        PanelHistorialDiagnosticos = new javax.swing.JPanel();
        PanelIngresarDatos = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIdDiagnostico = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dateDiagnostico = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcionDiag = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtIdLinea = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbEnfermedad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbProcesoLineaDiagnostico = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        btnAceptarLineaDiagnostico = new java.awt.Button();
        jLabel23 = new javax.swing.JLabel();
        cmbProcesoDiagnostico = new javax.swing.JComboBox<>();
        btnAceptarDiagnostico = new java.awt.Button();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEncabDiag = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaLineasDiag = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(77, 115, 129));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDivisor2.setBackground(new java.awt.Color(224, 123, 79));

        lblTitulo3.setAlignment(java.awt.Label.CENTER);
        lblTitulo3.setBackground(new java.awt.Color(26, 72, 91));
        lblTitulo3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(224, 123, 79));
        lblTitulo3.setText("MyPetCR");

        btnInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnInicio.setLabel("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnPerfil.setActionCommand("Perfil");
        btnPerfil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPerfil.setLabel("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        lblTitulo.setBackground(new java.awt.Color(224, 123, 79));
        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(26, 72, 91));
        lblTitulo.setText("EXPEDIENTE: ");

        javax.swing.GroupLayout pnlDivisor2Layout = new javax.swing.GroupLayout(pnlDivisor2);
        pnlDivisor2.setLayout(pnlDivisor2Layout);
        pnlDivisor2Layout.setHorizontalGroup(
            pnlDivisor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDivisor2Layout.createSequentialGroup()
                .addComponent(lblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnlDivisor2Layout.setVerticalGroup(
            pnlDivisor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDivisor2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDivisor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(pnlDivisor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        pnlTituloNotificaciones.setBackground(new java.awt.Color(26, 72, 91));
        pnlTituloNotificaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(77, 115, 129), new java.awt.Color(224, 123, 79), null, null));

        btnHistorialVacunas.setActionCommand("ECOMMERCE");
        btnHistorialVacunas.setBackground(new java.awt.Color(26, 72, 91));
        btnHistorialVacunas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHistorialVacunas.setForeground(new java.awt.Color(224, 123, 79));
        btnHistorialVacunas.setLabel("Historial Vacunas");
        btnHistorialVacunas.setPreferredSize(new java.awt.Dimension(170, 25));
        btnHistorialVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialVacunasActionPerformed(evt);
            }
        });

        btnRecetas.setActionCommand("ECOMMERCE");
        btnRecetas.setBackground(new java.awt.Color(26, 72, 91));
        btnRecetas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRecetas.setForeground(new java.awt.Color(224, 123, 79));
        btnRecetas.setLabel("Recetas");
        btnRecetas.setPreferredSize(new java.awt.Dimension(170, 25));
        btnRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecetasActionPerformed(evt);
            }
        });

        btnHistorialDiagnosticos.setActionCommand("ECOMMERCE");
        btnHistorialDiagnosticos.setBackground(new java.awt.Color(26, 72, 91));
        btnHistorialDiagnosticos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHistorialDiagnosticos.setForeground(new java.awt.Color(224, 123, 79));
        btnHistorialDiagnosticos.setLabel("Historial Diagnosticos");
        btnHistorialDiagnosticos.setPreferredSize(new java.awt.Dimension(170, 25));
        btnHistorialDiagnosticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialDiagnosticosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTituloNotificacionesLayout = new javax.swing.GroupLayout(pnlTituloNotificaciones);
        pnlTituloNotificaciones.setLayout(pnlTituloNotificacionesLayout);
        pnlTituloNotificacionesLayout.setHorizontalGroup(
            pnlTituloNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloNotificacionesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnHistorialDiagnosticos, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnHistorialVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloNotificacionesLayout.setVerticalGroup(
            pnlTituloNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloNotificacionesLayout.createSequentialGroup()
                .addGroup(pnlTituloNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRecetas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnHistorialVacunas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistorialDiagnosticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel2.add(pnlTituloNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 1010, 40));

        PanelRecetas.setBackground(new java.awt.Color(26, 72, 91));

        PanelIngresarDatos2.setBackground(new java.awt.Color(177, 189, 201));
        PanelIngresarDatos2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 204)));
        PanelIngresarDatos2.setPreferredSize(new java.awt.Dimension(330, 409));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("ID Mascota:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtIdReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdRecetaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("ID Receta:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Fecha Receta:");

        dateReceta.setDateFormatString("yyyy-MM-dd");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Numero Linea:");

        txtIdCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCliente4ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Medicamento:");

        cmbProceso5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultar Todos", "Consultar uno", "Insertar", "Actualizar", "Eliminar" }));
        cmbProceso5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProceso5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Lineas Receta");

        cmbProcesoLineaReceta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultar Todos", "Consultar uno", "Insertar", "Actualizar", "Eliminar" }));
        cmbProcesoLineaReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProcesoLineaRecetaActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Proceso:");

        btnAceptarLineaReceta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptarLineaReceta.setLabel("Aceptar");
        btnAceptarLineaReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarLineaRecetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdCliente4)
                            .addComponent(cmbProcesoLineaReceta, 0, 192, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAceptarLineaReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProceso5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProcesoLineaReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProceso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptarLineaReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Proceso:");

        cmbProcesoReceta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultar Todos", "Consultar uno", "Insertar", "Actualizar", "Eliminar" }));
        cmbProcesoReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProcesoRecetaActionPerformed(evt);
            }
        });

        btnAceptarReceta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptarReceta.setLabel("Aceptar");
        btnAceptarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRecetaActionPerformed(evt);
            }
        });

        txtIdMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMascotaActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("ID Veterinario:");

        txtIdVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVeterinarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresarDatos2Layout = new javax.swing.GroupLayout(PanelIngresarDatos2);
        PanelIngresarDatos2.setLayout(PanelIngresarDatos2Layout);
        PanelIngresarDatos2Layout.setHorizontalGroup(
            PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatos2Layout.createSequentialGroup()
                        .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(txtIdVeterinario))
                            .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                                        .addComponent(btnAceptarReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(204, 204, 204))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelIngresarDatos2Layout.createSequentialGroup()
                                .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel15))
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel31))
                                .addGap(24, 24, 24)
                                .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbProcesoReceta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdReceta)
                                    .addComponent(dateReceta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdMascota))))
                        .addGap(15, 15, 15))))
        );
        PanelIngresarDatos2Layout.setVerticalGroup(
            PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cmbProcesoReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatos2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatos2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatos2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIngresarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnAceptarReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setBackground(new java.awt.Color(153, 153, 153));

        tablaEncabRecetas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaEncabRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Receta", "ID Mascota", "Fecha Receta", "ID Vet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaEncabRecetas);
        if (tablaEncabRecetas.getColumnModel().getColumnCount() > 0) {
            tablaEncabRecetas.getColumnModel().getColumn(0).setHeaderValue("ID Receta");
        }

        jScrollPane3.setBackground(new java.awt.Color(153, 153, 153));

        tablaLineaReceta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaLineaReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Linea", "ID Receta", "Medicamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaLineaReceta);
        if (tablaLineaReceta.getColumnModel().getColumnCount() > 0) {
            tablaLineaReceta.getColumnModel().getColumn(0).setHeaderValue("ID Receta");
        }

        javax.swing.GroupLayout PanelRecetasLayout = new javax.swing.GroupLayout(PanelRecetas);
        PanelRecetas.setLayout(PanelRecetasLayout);
        PanelRecetasLayout.setHorizontalGroup(
            PanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRecetasLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelIngresarDatos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelRecetasLayout.setVerticalGroup(
            PanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelIngresarDatos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", PanelRecetas);

        PanelHistorialDeVacunas1.setBackground(new java.awt.Color(26, 72, 91));

        PanelIngresarDatos1.setBackground(new java.awt.Color(177, 189, 201));
        PanelIngresarDatos1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 204)));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Fecha Vacuna");

        btnAceptarVacuna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptarVacuna.setLabel("Aceptar");
        btnAceptarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarVacunaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtIdRegistroVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdRegistroVacunaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("ID Vacuna:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Vacuna:");

        dateVacuna.setDateFormatString("yyyy-MM-dd");

        cmbVacuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultar Todos", "Consultar uno", "Insertar", "Actualizar", "Eliminar" }));
        cmbVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVacunaActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Proceso:");

        cmbProcesoVacuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultar Todos", "Consultar uno", "Insertar", "Actualizar", "Eliminar" }));
        cmbProcesoVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProcesoVacunaActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("ID Mascota:");

        txtIdMascotaVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMascotaVacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresarDatos1Layout = new javax.swing.GroupLayout(PanelIngresarDatos1);
        PanelIngresarDatos1.setLayout(PanelIngresarDatos1Layout);
        PanelIngresarDatos1Layout.setHorizontalGroup(
            PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatos1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatos1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptarVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
            .addGroup(PanelIngresarDatos1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelIngresarDatos1Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(60, 60, 60)
                        .addComponent(txtIdMascotaVac, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel20)
                        .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatos1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatos1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(60, 60, 60)
                                    .addComponent(txtIdRegistroVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(PanelIngresarDatos1Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addGap(73, 73, 73)
                            .addComponent(cmbProcesoVacuna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelIngresarDatos1Layout.setVerticalGroup(
            PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatos1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProcesoVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdRegistroVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdMascotaVac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIngresarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(btnAceptarVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jScrollPane6.setBackground(new java.awt.Color(153, 153, 153));

        tablaHistorialVacunas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaHistorialVacunas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Registro", "ID Mascota", "ID Vacuna", "Fecha Vacuna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaHistorialVacunas);

        javax.swing.GroupLayout PanelHistorialDeVacunas1Layout = new javax.swing.GroupLayout(PanelHistorialDeVacunas1);
        PanelHistorialDeVacunas1.setLayout(PanelHistorialDeVacunas1Layout);
        PanelHistorialDeVacunas1Layout.setHorizontalGroup(
            PanelHistorialDeVacunas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHistorialDeVacunas1Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelIngresarDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelHistorialDeVacunas1Layout.setVerticalGroup(
            PanelHistorialDeVacunas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelIngresarDatos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", PanelHistorialDeVacunas1);

        PanelHistorialDiagnosticos.setBackground(new java.awt.Color(26, 72, 91));

        PanelIngresarDatos.setBackground(new java.awt.Color(177, 189, 201));
        PanelIngresarDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 204)));
        PanelIngresarDatos.setPreferredSize(new java.awt.Dimension(330, 409));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Descrpción");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtIdDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDiagnosticoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("ID Diagnostico:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Fecha Diagnostico:");

        dateDiagnostico.setDateFormatString("yyyy-MM-dd");

        jTextAreaDescripcionDiag.setColumns(20);
        jTextAreaDescripcionDiag.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcionDiag);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Numero Linea");

        txtIdLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLineaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Enfermedad");

        cmbEnfermedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultar Todos", "Consultar uno", "Insertar", "Actualizar", "Eliminar" }));
        cmbEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnfermedadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Lineas Diagnostico");

        cmbProcesoLineaDiagnostico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultar Todos", "Consultar uno", "Insertar", "Actualizar", "Eliminar" }));
        cmbProcesoLineaDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProcesoLineaDiagnosticoActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Proceso:");

        btnAceptarLineaDiagnostico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptarLineaDiagnostico.setLabel("Aceptar");
        btnAceptarLineaDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarLineaDiagnosticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdLinea)
                            .addComponent(cmbProcesoLineaDiagnostico, 0, 192, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAceptarLineaDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProcesoLineaDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptarLineaDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Proceso:");

        cmbProcesoDiagnostico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultar Todos", "Consultar uno", "Insertar", "Actualizar", "Eliminar" }));
        cmbProcesoDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProcesoDiagnosticoActionPerformed(evt);
            }
        });

        btnAceptarDiagnostico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptarDiagnostico.setLabel("Aceptar");
        btnAceptarDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarDiagnosticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresarDatosLayout = new javax.swing.GroupLayout(PanelIngresarDatos);
        PanelIngresarDatos.setLayout(PanelIngresarDatosLayout);
        PanelIngresarDatosLayout.setHorizontalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatosLayout.createSequentialGroup()
                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelIngresarDatosLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                        .addComponent(btnAceptarDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(204, 204, 204))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelIngresarDatosLayout.createSequentialGroup()
                                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel23))
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatosLayout.createSequentialGroup()
                                        .addComponent(cmbProcesoDiagnostico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addComponent(txtIdDiagnostico))))
                        .addGap(15, 15, 15))))
        );
        PanelIngresarDatosLayout.setVerticalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbProcesoDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtIdDiagnostico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptarDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane4.setBackground(new java.awt.Color(153, 153, 153));

        tablaEncabDiag.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaEncabDiag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Diagnostico", "Descripcion", "Fecha Diagnost.", "ID Mascota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaEncabDiag);
        if (tablaEncabDiag.getColumnModel().getColumnCount() > 0) {
            tablaEncabDiag.getColumnModel().getColumn(0).setHeaderValue("ID Receta");
        }

        jScrollPane5.setBackground(new java.awt.Color(153, 153, 153));

        TablaLineasDiag.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaLineasDiag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Linea", "ID Diagnost.", "Enfermedad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TablaLineasDiag);
        if (TablaLineasDiag.getColumnModel().getColumnCount() > 0) {
            TablaLineasDiag.getColumnModel().getColumn(0).setHeaderValue("ID Receta");
        }

        javax.swing.GroupLayout PanelHistorialDiagnosticosLayout = new javax.swing.GroupLayout(PanelHistorialDiagnosticos);
        PanelHistorialDiagnosticos.setLayout(PanelHistorialDiagnosticosLayout);
        PanelHistorialDiagnosticosLayout.setHorizontalGroup(
            PanelHistorialDiagnosticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHistorialDiagnosticosLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelHistorialDiagnosticosLayout.setVerticalGroup(
            PanelHistorialDiagnosticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", PanelHistorialDiagnosticos);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 66, 1020, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        new Venta_Main();
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        new Ven_Perfil();
        this.dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnHistorialVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVacunasActionPerformed
       jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnHistorialVacunasActionPerformed

    private void btnRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecetasActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnRecetasActionPerformed

    private void btnHistorialDiagnosticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialDiagnosticosActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnHistorialDiagnosticosActionPerformed

    private void btnAceptarLineaDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarLineaDiagnosticoActionPerformed
/*
        int proceso = cmbProceso.getSelectedIndex();
        filasAfectadas = 0;

        if (proceso == 0) {// se consultan todas las Mascotas de ese cliente

            if (hayIdUsuario()) {

                tabla = MascotasAccess.getAllClientPets(idUsuario);

                if (!tabla.isEmpty()) {
                    Auxiliar.addTabla(tabla, tablaMascotas);
                }
            }

        } else if (proceso == 1) { //Consultar por una mascota en especifico

            if (hayIdMascota()) {

                tabla = MascotasAccess.getPet(idMascota);

                if (!tabla.isEmpty()) {
                    Auxiliar.addTabla(tabla, tablaMascotas);
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo encontrar", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else if (proceso == 2) { //Insertar una mascota
            if (getValores()) { //Obtener los valores de los textFields, etc;
                filasAfectadas = MascotasAccess.intsetPet(idUsuario, nombre, edad, Sexo);
                JOptionPane.showMessageDialog(null, "Se registro la mascota correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Debe Completar todos los datos para poder Ingresar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (proceso == 3) { //Actualizar una mascota
            if (getValores()) { //Obtener los valores de los textFields, etc;
                filasAfectadas = MascotasAccess.updatePet(idUsuario, nombre, edad, Sexo);
                JOptionPane.showMessageDialog(null, "Se registro el Cliente Correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Debe Completar todos los datos para poder Actualizar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (proceso == 4) { //Eliminar una mascota

            if (hayIdMascota()) {

                filasAfectadas = MascotasAccess.deletePet(idMascota);

                if (filasAfectadas != 0) {
                    JOptionPane.showMessageDialog(null, "Se Elimino el Cliente Correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo encontrar", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
*/
    }//GEN-LAST:event_btnAceptarLineaDiagnosticoActionPerformed

    private void txtIdDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDiagnosticoActionPerformed

    private void txtIdLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLineaActionPerformed

    private void cmbEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnfermedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEnfermedadActionPerformed

    private void btnAceptarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarVacunaActionPerformed
        int proceso = cmbProcesoVacuna.getSelectedIndex();
        System.out.println(proceso);
        filasAfectadas = 0;
        ArrayList<ArrayList<String>> tabla= new ArrayList<ArrayList<String>>();
        switch (proceso){
            case 0://Consultar uno
                tabla = RegistroVacunasAccess.getAllRegistrosVacunas();
                if (!tabla.isEmpty()) {
                    Auxiliar.addTabla(tabla, tablaHistorialVacunas);
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo consultar la tabla",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case 1://Consultar Todos
                 tabla= RegistroVacunasAccess.getRegistroVacuna(Integer.parseInt(txtIdRegistroVacuna.getText()));
                if (!tabla.isEmpty()) {
                    Auxiliar.addTabla(tabla, tablaHistorialVacunas);
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo consultar la tabla",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
        
                break;
            
            case 2: //insertar
                txtIdRegistroVacuna.setText("0");

                if (getValoresVacuna()){
                    /*
                    producto = new Productos(idProductos, Nombre, Categoria, cantidadTotal, 
                            (int)Precio, imagen);
                    GLOBAL.addProducto(producto);
                    JOptionPane.showMessageDialog(null, 
                            "Producto agregado con exito");
                    */
                   RegistroVacunasAccess.insertRegistroVacuna(IDMascota, IDVacuna);

                }
                txtIdRegistroVacuna.setText(""); 
                break;
            case 3://Actualizar
                if (txtIdRegistroVacuna.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Debe ingresar un ID de registro de vacuna", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                }
                if (getValoresVacuna()){
                    RegistroVacunasAccess.updateRegistroVacuna(IDRegistro, 
                            IDMascota, IDVacuna,fechaVacuna);
                    JOptionPane.showMessageDialog(null, 
                            "Producto modificado con exito");
                }
                break;
            case 4://Eliminar
                if (RegistroVacunasAccess.deleteRegistroVacuna(Integer.parseInt(txtIdRegistroVacuna.getText()))!=0){
                    JOptionPane.showMessageDialog(null, 
                            "Producto eliminado con exito");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el producto",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
    }//GEN-LAST:event_btnAceptarVacunaActionPerformed

    private void txtIdRegistroVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdRegistroVacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRegistroVacunaActionPerformed

    private void cmbVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVacunaActionPerformed

    private void cmbProcesoVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProcesoVacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProcesoVacunaActionPerformed

    private void cmbProcesoDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProcesoDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProcesoDiagnosticoActionPerformed

    private void cmbProcesoLineaDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProcesoLineaDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProcesoLineaDiagnosticoActionPerformed

    private void btnAceptarDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarDiagnosticoActionPerformed

    private void txtIdRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRecetaActionPerformed

    private void txtIdCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCliente4ActionPerformed

    private void cmbProceso5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProceso5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProceso5ActionPerformed

    private void cmbProcesoLineaRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProcesoLineaRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProcesoLineaRecetaActionPerformed

    private void btnAceptarLineaRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarLineaRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarLineaRecetaActionPerformed

    private void cmbProcesoRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProcesoRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProcesoRecetaActionPerformed

    private void btnAceptarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarRecetaActionPerformed

    private void txtIdMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMascotaActionPerformed

    private void txtIdVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVeterinarioActionPerformed

    private void txtIdMascotaVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMascotaVacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMascotaVacActionPerformed

    private boolean getValoresVacuna () {
        
        
    //private int IDMascota;
    
    //-----Vacunas----
    //int IDVacuna;
    // Date fechaVacuna;
        //validar int
        try{
        IDRegistro = Integer.parseInt(txtIdRegistroVacuna.getText());
        IDMascota = Integer.parseInt(txtIdMascotaVac.getText());
        IDVacuna= cmbVacuna.getSelectedIndex();
        String tmp;
        tmp = ((JTextField) dateVacuna.getDateEditor().getUiComponent()).getText();
        if (tmp.equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar fechas validas", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            fechaVacuna = Date.valueOf(tmp);
            return true;
        }
        
        }catch(Exception e){
            return false;
        }finally{
            
        }
    }


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHistorialDeVacunas1;
    private javax.swing.JPanel PanelHistorialDiagnosticos;
    private javax.swing.JPanel PanelIngresarDatos;
    private javax.swing.JPanel PanelIngresarDatos1;
    private javax.swing.JPanel PanelIngresarDatos2;
    private javax.swing.JPanel PanelRecetas;
    private javax.swing.JTable TablaLineasDiag;
    private java.awt.Button btnAceptarDiagnostico;
    private java.awt.Button btnAceptarLineaDiagnostico;
    private java.awt.Button btnAceptarLineaReceta;
    private java.awt.Button btnAceptarReceta;
    private java.awt.Button btnAceptarVacuna;
    private java.awt.Button btnHistorialDiagnosticos;
    private java.awt.Button btnHistorialVacunas;
    private java.awt.Button btnInicio;
    private java.awt.Button btnPerfil;
    private java.awt.Button btnRecetas;
    private javax.swing.JComboBox<String> cmbEnfermedad;
    private javax.swing.JComboBox<String> cmbProceso5;
    private javax.swing.JComboBox<String> cmbProcesoDiagnostico;
    private javax.swing.JComboBox<String> cmbProcesoLineaDiagnostico;
    private javax.swing.JComboBox<String> cmbProcesoLineaReceta;
    private javax.swing.JComboBox<String> cmbProcesoReceta;
    private javax.swing.JComboBox<String> cmbProcesoVacuna;
    private javax.swing.JComboBox<String> cmbVacuna;
    private com.toedter.calendar.JDateChooser dateDiagnostico;
    private com.toedter.calendar.JDateChooser dateReceta;
    private com.toedter.calendar.JDateChooser dateVacuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaDescripcionDiag;
    private java.awt.Label lblTitulo;
    private java.awt.Label lblTitulo3;
    private javax.swing.JPanel pnlDivisor2;
    private javax.swing.JPanel pnlTituloNotificaciones;
    private javax.swing.JTable tablaEncabDiag;
    private javax.swing.JTable tablaEncabRecetas;
    private javax.swing.JTable tablaHistorialVacunas;
    private javax.swing.JTable tablaLineaReceta;
    private javax.swing.JTextField txtIdCliente4;
    private javax.swing.JTextField txtIdDiagnostico;
    private javax.swing.JTextField txtIdLinea;
    private javax.swing.JTextField txtIdMascota;
    private javax.swing.JTextField txtIdMascotaVac;
    private javax.swing.JTextField txtIdReceta;
    private javax.swing.JTextField txtIdRegistroVacuna;
    private javax.swing.JTextField txtIdVeterinario;
    // End of variables declaration//GEN-END:variables
}
