package Ventanas;

import Auxiliares.Auxiliar;
import Conexiones.CitasAccess;
import Conexiones.MascotasAccess;
import Conexiones.NotificacionesAccess;
import Conexiones.SucursalesAccess;
import Enums.TipoUsuario;
import Objetos.GLOBAL;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Ven_Cita extends javax.swing.JFrame {

    private ArrayList<ArrayList<String>> sucursales;
    private ArrayList<ArrayList<String>> veterinarios;
    private ArrayList<ArrayList<String>> mascotas;
    private ArrayList<ArrayList<String>> citasFuturas;

    public Ven_Cita() {
        initComponents();
        changeVentana();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void changeVentana() {
        jComboBoxSucursal.removeAllItems();
        sucursales = SucursalesAccess.getAllSucursal();
        for (ArrayList<String> fila : sucursales) {
            jComboBoxSucursal.addItem(fila.get(1)); //Nombre Sucursal
        }

        if (GLOBAL.user.getTipo().equals(TipoUsuario.CLIENTE)) {
            jComboBoxMascota.removeAllItems();
            jComboBoxCitas.removeAllItems();
            jLabelCliente.setText(" ");

            citasFuturas = CitasAccess.getAllFutureClientsAppointments(GLOBAL.user.getID());
            if (citasFuturas != null) {
                for (ArrayList<String> fila : citasFuturas) {
                    jComboBoxCitas.addItem(fila.get(0)); //IDCita
                }
            }

            mascotas = MascotasAccess.getAllClientPets(GLOBAL.user.getID());
            if (mascotas != null) {
                for (ArrayList<String> fila : mascotas) {
                    jComboBoxMascota.addItem(fila.get(1)); //Nombre Mascota
                }
            }
            jComboBoxVeterinario.setEditable(false);

        } else if (GLOBAL.user.getTipo().equals(TipoUsuario.ADMIN) || GLOBAL.user.getTipo().equals(TipoUsuario.GERENTE)) {
            jComboBoxMascota.removeAllItems();
            jComboBoxCitas.removeAllItems();

            citasFuturas = CitasAccess.getAllFutureAppointments();
            if (citasFuturas != null) {
                for (ArrayList<String> fila : citasFuturas) {
                    jComboBoxCitas.addItem(fila.get(0)); //IDCita
                }
            }
            mascotas = MascotasAccess.getAllPetsWithClients(); //Aqui todas las mascotas con nombres de clientes too
            if (mascotas != null) {
                for (ArrayList<String> fila : mascotas) {
                    jComboBoxMascota.addItem(fila.get(1)); //Nombre Mascota
                }
            }

        } else {
            //Veterinario no puede cancelar citas
            cmbProceso.removeAllItems();
            cmbProceso.addItem("Agendar una cita");

            jComboBoxMascota.removeAllItems();

            mascotas = MascotasAccess.getAllPetsWithClients(); //Aqui todas las mascotas con nombres de clientes too
            if (mascotas != null) {
                for (ArrayList<String> fila : mascotas) {
                    jComboBoxMascota.addItem(fila.get(1)); //Nombre Mascota
                }
            }
        }
    }

    private void colocarVetsDisponibles(String fecha, String hora) {
        jComboBoxVeterinario.removeAllItems();

        veterinarios = CitasAccess.ExtraerVetsDisponibles(fecha, hora); // aqui el sp que saca los vets
        if (veterinarios != null) {
            for (ArrayList<String> fila : veterinarios) {
                jComboBoxVeterinario.addItem(fila.get(1)); //Nombre veterinario
            }
        }

        //EncontrarVets Disponibles
    }

    private boolean validarCmb() {
        return jComboBoxVeterinario.getSelectedIndex() != -1
                && jComboBoxMascota.getSelectedIndex() != -1
                && jComboBoxSucursal.getSelectedIndex() != -1
                && Auxiliar
                        .validarFecha(
                                cmbDia.getSelectedItem().toString() + "/"
                                + cmbMes.getSelectedItem().toString() + "/"
                                + cmbAnno.getSelectedItem().toString(),
                                 "d/M/yyyy")
                && cmbAnno.getSelectedIndex() != -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelIngresarDatos = new javax.swing.JPanel();
        cmbProceso = new javax.swing.JComboBox<>();
        pnlDivisor2 = new javax.swing.JPanel();
        lblTitulo3 = new java.awt.Label();
        btnInicio = new java.awt.Button();
        btnPerfil = new java.awt.Button();
        lblCitas = new java.awt.Label();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAgendar = new javax.swing.JPanel();
        jComboBoxSucursal = new javax.swing.JComboBox<>();
        jComboBoxMascota = new javax.swing.JComboBox<>();
        jComboBoxVeterinario = new javax.swing.JComboBox<>();
        cmbAnno = new javax.swing.JComboBox<>();
        jLabelCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAgendar = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        cmbHora = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        cmbMes = new javax.swing.JComboBox<>();
        jPanelCancelar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCitas = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnCancelar = new java.awt.Button();
        txtMascota = new javax.swing.JLabel();
        txtVeterinario = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        txtSucursal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(77, 115, 129));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIngresarDatos.setBackground(new java.awt.Color(177, 189, 201));
        PanelIngresarDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 204)));

        cmbProceso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agendar una cita", "Cancelar una cita" }));
        cmbProceso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProcesoItemStateChanged(evt);
            }
        });
        cmbProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProcesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresarDatosLayout = new javax.swing.GroupLayout(PanelIngresarDatos);
        PanelIngresarDatos.setLayout(PanelIngresarDatosLayout);
        PanelIngresarDatosLayout.setHorizontalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatosLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(cmbProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        PanelIngresarDatosLayout.setVerticalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(cmbProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );

        jPanel2.add(PanelIngresarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 64, -1, 440));

        pnlDivisor2.setBackground(new java.awt.Color(224, 123, 79));

        lblTitulo3.setAlignment(java.awt.Label.CENTER);
        lblTitulo3.setBackground(new java.awt.Color(26, 72, 91));
        lblTitulo3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(224, 123, 79));
        lblTitulo3.setText("MyPetCR");

        btnInicio.setLabel("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnPerfil.setActionCommand("Perfil");
        btnPerfil.setLabel("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        lblCitas.setBackground(new java.awt.Color(224, 123, 79));
        lblCitas.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblCitas.setForeground(new java.awt.Color(26, 72, 91));
        lblCitas.setText("CITAS");

        javax.swing.GroupLayout pnlDivisor2Layout = new javax.swing.GroupLayout(pnlDivisor2);
        pnlDivisor2.setLayout(pnlDivisor2Layout);
        pnlDivisor2Layout.setHorizontalGroup(
            pnlDivisor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDivisor2Layout.createSequentialGroup()
                .addComponent(lblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnlDivisor2Layout.setVerticalGroup(
            pnlDivisor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDivisor2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDivisor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(pnlDivisor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 979, -1));

        jPanelAgendar.setBackground(new java.awt.Color(177, 189, 201));
        jPanelAgendar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxSucursal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucursal1", "Sucursal2", "Sucursal3" }));
        jPanelAgendar.add(jComboBoxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 226, 30));

        jComboBoxMascota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mascota1", "Mascota" }));
        jComboBoxMascota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMascotaItemStateChanged(evt);
            }
        });
        jComboBoxMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMascotaActionPerformed(evt);
            }
        });
        jPanelAgendar.add(jComboBoxMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 250, 30));

        jComboBoxVeterinario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelAgendar.add(jComboBoxVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 226, 30));

        cmbAnno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbAnno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028" }));
        cmbAnno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAnnoItemStateChanged(evt);
            }
        });
        jPanelAgendar.add(cmbAnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 70, 30));

        jLabelCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCliente.setText("Cliente:");
        jPanelAgendar.add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 219, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AGENDAR CITA");
        jPanelAgendar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 580, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Sucursal");
        jPanelAgendar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 219, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Fecha y Hora");
        jPanelAgendar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 230, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Veterinario");
        jPanelAgendar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 226, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Complete los datos para agendar su cita:");
        jPanelAgendar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 580, -1));

        btnAgendar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgendar.setLabel("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        jPanelAgendar.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 356, 171, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Mascota");
        jPanelAgendar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 219, -1));

        cmbHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00" }));
        cmbHora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbHoraItemStateChanged(evt);
            }
        });
        jPanelAgendar.add(cmbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 80, 30));

        cmbDia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbDia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDiaItemStateChanged(evt);
            }
        });
        jPanelAgendar.add(cmbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 50, 30));

        cmbMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMesItemStateChanged(evt);
            }
        });
        jPanelAgendar.add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 50, 30));

        jTabbedPane1.addTab("tab1", jPanelAgendar);

        jPanelCancelar.setBackground(new java.awt.Color(177, 189, 201));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CANCELAR CITA");

        jComboBoxCitas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxCitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cita1", "Cita2", "Cita3" }));
        jComboBoxCitas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCitasItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Seleccione la cita que desea cancelar:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Mascota:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Veterinario asignado: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Fecha de la cita:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Hora de la cita:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Sucursal de la cita:");

        btnCancelar.setActionCommand("Cancelar");
        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtMascota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMascota.setForeground(new java.awt.Color(51, 51, 51));
        txtMascota.setText("Mascota:");

        txtVeterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVeterinario.setForeground(new java.awt.Color(51, 51, 51));
        txtVeterinario.setText("Mascota:");

        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(51, 51, 51));
        txtFecha.setText("Mascota:");

        txtHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHora.setForeground(new java.awt.Color(51, 51, 51));
        txtHora.setText("Mascota:");

        txtSucursal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSucursal.setForeground(new java.awt.Color(51, 51, 51));
        txtSucursal.setText("Mascota:");

        javax.swing.GroupLayout jPanelCancelarLayout = new javax.swing.GroupLayout(jPanelCancelar);
        jPanelCancelar.setLayout(jPanelCancelarLayout);
        jPanelCancelarLayout.setHorizontalGroup(
            jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCancelarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCancelarLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addGroup(jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCitas, 0, 135, Short.MAX_VALUE)))
                    .addGroup(jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelCancelarLayout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCancelarLayout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCancelarLayout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCancelarLayout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCancelarLayout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelCancelarLayout.setVerticalGroup(
            jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCancelarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("tab3", jPanelCancelar);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 24, -1, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProcesoActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        new Venta_Main();
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        new Ven_Perfil();
        this.dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed

        String fecha = cmbDia.getSelectedItem().toString() + "/" + cmbMes.getSelectedItem().toString() + "/" + cmbAnno.getSelectedItem().toString();
        if (validarCmb()) {
            
            //Notificación
            ArrayList<String> mascota = MascotasAccess.getPet(
                    Integer.parseInt(mascotas.get(jComboBoxMascota.getSelectedIndex()
                    ).get(0))).get(0);
            int idCliente = Integer.parseInt(mascota.get(0));
            NotificacionesAccess.intsetAppointment(2,
                    "Se agendo una cita para el dia: " + fecha
                    + " a la hora: " + cmbHora.getSelectedItem().toString(),
                    idCliente,
                    Integer.parseInt(veterinarios.get(jComboBoxVeterinario.getSelectedIndex()).get(0)));
            //Agendar Cita

            CitasAccess.intsetAppointment(fecha,
                    cmbHora.getSelectedItem().toString(),
                    Integer.parseInt(mascotas.get(jComboBoxMascota.getSelectedIndex()).get(0)),
                    Integer.parseInt(veterinarios.get(jComboBoxVeterinario.getSelectedIndex()).get(0)),
                    Integer.parseInt(sucursales.get(jComboBoxSucursal.getSelectedIndex()).get(0)));
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione los datos necesarios");
        }

    }//GEN-LAST:event_btnAgendarActionPerformed

    private void cmbProcesoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProcesoItemStateChanged
        jTabbedPane1.setSelectedIndex(cmbProceso.getSelectedIndex());
    }//GEN-LAST:event_cmbProcesoItemStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //Notificación
        ArrayList<String> cita = CitasAccess.GetAppointment(
                Integer.parseInt(jComboBoxCitas.getSelectedItem().toString())
        ).get(0);
        int idVet = Integer.parseInt(cita.get(3));
        NotificacionesAccess.intsetAppointment(3,
                "Se cancelo la cita asiganada al veterinario: " + idVet
                + ", el dia: " + citasFuturas.get(jComboBoxCitas.getSelectedIndex()).get(1)
                + " a la hora: " + citasFuturas.get(jComboBoxCitas.getSelectedIndex()).get(2),
                Integer.parseInt(cita.get(5)), idVet);
        //Cancelar Cita
        CitasAccess.deleteAppointment(Integer.parseInt(jComboBoxCitas.getSelectedItem().toString()));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jComboBoxCitasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCitasItemStateChanged
        //AQUI VA EL SET DE LA INFO DE LA CITA

        if (citasFuturas != null) {
            txtMascota.setText(citasFuturas.get(jComboBoxCitas.getSelectedIndex()).get(3));
            txtVeterinario.setText(citasFuturas.get(jComboBoxCitas.getSelectedIndex()).get(4));
            txtFecha.setText(citasFuturas.get(jComboBoxCitas.getSelectedIndex()).get(1));
            txtHora.setText(citasFuturas.get(jComboBoxCitas.getSelectedIndex()).get(2));
            txtSucursal.setText(citasFuturas.get(jComboBoxCitas.getSelectedIndex()).get(5));
        }
    }//GEN-LAST:event_jComboBoxCitasItemStateChanged

    private void jComboBoxMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMascotaActionPerformed

    }//GEN-LAST:event_jComboBoxMascotaActionPerformed

    private void jComboBoxMascotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMascotaItemStateChanged
        if (!GLOBAL.user.getTipo().equals(TipoUsuario.CLIENTE)) {
            jLabelCliente.setText("Cliente: " + mascotas.get(jComboBoxMascota.getSelectedIndex()).get(4));
        }
    }//GEN-LAST:event_jComboBoxMascotaItemStateChanged

    private void cmbAnnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAnnoItemStateChanged
        String fecha = cmbDia.getSelectedItem().toString() + "/" + cmbMes.getSelectedItem().toString() + "/" + cmbAnno.getSelectedItem().toString();
        if (Auxiliar.validarFecha(fecha, "d/M/yyyy")) {
            colocarVetsDisponibles(fecha, cmbHora.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbAnnoItemStateChanged

    private void cmbHoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbHoraItemStateChanged
        String fecha = cmbDia.getSelectedItem().toString() + "/" + cmbMes.getSelectedItem().toString() + "/" + cmbAnno.getSelectedItem().toString();
        if (Auxiliar.validarFecha(fecha, "d/M/yyyy")) {
            colocarVetsDisponibles(fecha, cmbHora.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbHoraItemStateChanged

    private void cmbDiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDiaItemStateChanged
        String fecha = cmbDia.getSelectedItem().toString() + "/" + cmbMes.getSelectedItem().toString() + "/" + cmbAnno.getSelectedItem().toString();
        if (Auxiliar.validarFecha(fecha, "d/M/yyyy")) {
            colocarVetsDisponibles(fecha, cmbHora.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbDiaItemStateChanged

    private void cmbMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMesItemStateChanged
        String fecha = cmbDia.getSelectedItem().toString() + "/" + cmbMes.getSelectedItem().toString() + "/" + cmbAnno.getSelectedItem().toString();
        if (Auxiliar.validarFecha(fecha, "d/M/yyyy")) {
            colocarVetsDisponibles(fecha, cmbHora.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbMesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIngresarDatos;
    private java.awt.Button btnAgendar;
    private java.awt.Button btnCancelar;
    private java.awt.Button btnInicio;
    private java.awt.Button btnPerfil;
    private javax.swing.JComboBox<String> cmbAnno;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbHora;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<String> cmbProceso;
    private javax.swing.JComboBox<String> jComboBoxCitas;
    private javax.swing.JComboBox<String> jComboBoxMascota;
    private javax.swing.JComboBox<String> jComboBoxSucursal;
    private javax.swing.JComboBox<String> jComboBoxVeterinario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAgendar;
    private javax.swing.JPanel jPanelCancelar;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label lblCitas;
    private java.awt.Label lblTitulo3;
    private javax.swing.JPanel pnlDivisor2;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtMascota;
    private javax.swing.JLabel txtSucursal;
    private javax.swing.JLabel txtVeterinario;
    // End of variables declaration//GEN-END:variables
}
